### ISSUE TITLE
Automatyczny restart zmora-judge po crashu

### ISSUE THREAD

**Issue by marcmos** [zmora-agh/zmora-overlay#1]
Wnioskiem ze zmora-agh/zmora-judge#19 jest napisanie skryptu, który będzie restartował usługę po crashu. W tym momencie sędzia jest uruchamiany przez OpenRC, więc być może wystarczy rozwiązanie opisane na [Gentoo Wiki](https://wiki.gentoo.org/wiki/OpenRC#Automatic_respawning_crashed_services).

**Comment by maxmati** [comment]
Na tyle ile czytałem to nie ma opcji żeby ustawić opcji i restart wykonywał się automatycznie, trzeba byłoby uruchomić jakiś skrypt w cronie czy coś podobnego. Dlatego wydaje mi się że lepiej pójść w stronę monitoringu całej solucji i ewentualnych maili z informacjami że coś jest nie tak.

**Comment by maxmati** [comment]
@marcmos z tego co mi się wydaje to po zdokeryzowaniu judge issue jest nieaktualne?
